language: php
php:
  - '7.3'

install:
    - composer self-update
    - make install

script:
    - make lint test

services:
    - postgresql

before_script:
    - cp .env.travis .env
    - mysql -e 'create database homestead_test;'
    - php artisan migrate --no-interaction
